version: "3"
services:
  contacts_api:
    # restart: on-failure
    container_name: contacts_api
    build: ./
    volumes:
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    networks:
      - mysql_network
    ports:
    - 8080:8080
    environment:
      MYSQL_DB_HOST: mysql # must be the name of the mysql container

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - mysql_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contactsapi
      # MYSQL_USER: contactsapi
      # MYSQL_PASSWORD: contactsapi
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysqlDatabase:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=contactsapi --password=contactsapi--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  mysqlDatabase:

networks:
  mysql_network:
    external: true
